export const azTracklist: string[] = [
  "mu tate — they're with you always",
  "express rising — neighborhood",
  "chaos in the cbd — trust is key/luxury motivation",
  "skee mask — session add",
  "slauson malone — challenger",
  "bing & ruth — as much as possible",
  "shinichi atobe — so good so right 2",
  "king krule — wednesday overcast",
  "concave reflection — lethal crush",
  "ulla — something i can't show",
  "james blake — not long now",
  "farben — so much love",
  "supreems — soft spring",
  "cousin — padda",
  "steve sobs — walking the cow*",
  "tim hecker — amps, drugs, mellotron",
  "duke hugh — butterflies",
  "helion — i'll see it when i believe it",
  "mount kimbie — carbonated",
  "jonny greenwood — back beyond",
  "terekke — 2 the world",
  "beatrice dillon — halfway",
  "the field — from here we go sublime",
  "al wootton — doxa",
  "mica levi & oliver coates — say goodbye to everyone",
  "elori saxl — wave iii",
  "aspetuck — concussion protocol",
  "salamanda — mirror mirror",
  "animal collective — banshee beat",
  "cicada ensemble — murmuration clip",
  "gas — konigsforst 6",
  "rozi plain — conditions",
  "dj healer — love.",
  "physical therapy — male tears",
  "persuasion — pure delusion",
  "ben bondy — ayymos",
  "spencer zahn — ost",
  "ezekiel honig — between bridges",
  "nina simone — twelfth of never",
  "ulla — blush",
  "being left undone — IIIIIIIIIIIIIIIIIII",
  "mica levi — tears",
  "with my hands out — mount eerie",
];

export const jhTrackList = [
  "1 - Bangs",
  "2 - Peach",
  "3 - Pallet",
  "4 -	Tame One",
  "5 -	Jekyll/Hyde	",
  "6 -	Expectation/Reality",
];

export const gumptionTrackList = [
  "1 - Heathering",
  "2 - Come Back From It",
  "3 - To Live With",
  "4 - Desired Things",
  "5 - Nothing Moved",
  "6 - Gumption",
  "7 - I Turned In",
  "8 - Who Will I Be in the Morning?",
];

export const LCLtrackList = [
  "1 - '22",
  "2 - These Days",
  "3 - Velocity! What About The Intertia",
  "4 - Entropy Increasing",
];
